# Generated by Django 5.0.6 on 2024-06-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='eventsUpdates',
        ),
    ]
