# Generated by Django 5.0.6 on 2024-06-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0003_rename_news_eventsupdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventsUpdates',
            new_name='Updates',
        ),
    ]
