# Generated by Django 5.0.6 on 2024-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0005_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='picture',
        ),
        migrations.AddField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(null=True, upload_to='athlete_photos/'),
        ),
    ]
