# Generated by Django 5.0.6 on 2024-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0006_remove_athlete_picture_athlete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='news/')),
            ],
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
