# Generated by Django 5.0.6 on 2024-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0007_news_delete_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='training/')),
            ],
        ),
    ]
