# Generated by Django 5.0.6 on 2024-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk', '0008_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
